DROP TABLE IF EXISTS measurement;
DROP TABLE IF EXISTS sensor;

CREATE TABLE sensor
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR UNIQUE NOT NULL,
    create_date TIMESTAMP
);

CREATE TABLE measurement
(
    id          INT GENERATED BY DEFAULT AS IDENTITY,
    date_time   TIMESTAMP,
    sensor_id   INT REFERENCES sensor (id) NOT NULL,
    temperature FLOAT                      NOT NULL,
    raining     BOOLEAN                    NOT NULL
);

